// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nsys.io/api/ntypes/file_ntypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nsys.Api.Ntypes {

  /// <summary>Holder for reflection information generated from nsys.io/api/ntypes/file_ntypes.proto</summary>
  public static partial class FileNtypesReflection {

    #region Descriptor
    /// <summary>File descriptor for nsys.io/api/ntypes/file_ntypes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FileNtypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRuc3lzLmlvL2FwaS9udHlwZXMvZmlsZV9udHlwZXMucHJvdG8SD25zeXMu",
            "YXBpLm50eXBlcxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byIrCgdSYXdG",
            "aWxlEgwKBGRhdGEYASABKAwSEgoKc2hhNTEyXzI1NhgCIAEoDCKtAQoLR2Vu",
            "ZXJpY0ZpbGUSDAoEbmFtZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIm",
            "CghtZXRhZGF0YRgDIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSFwoPb3Jp",
            "Z2luX2Jhc2VuYW1lGAQgASgJEg4KBmxlbmd0aBgFIAEoDRIqCghyYXdfZmls",
            "ZRgGIAEoCzIYLm5zeXMuYXBpLm50eXBlcy5SYXdGaWxlQhRaEm5zeXMuaW8v",
            "YXBpL250eXBlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nsys.Api.Ntypes.RawFile), global::Nsys.Api.Ntypes.RawFile.Parser, new[]{ "Data", "Sha512256" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nsys.Api.Ntypes.GenericFile), global::Nsys.Api.Ntypes.GenericFile.Parser, new[]{ "Name", "Description", "Metadata", "OriginBasename", "Length", "RawFile" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RawFile : pb::IMessage<RawFile> {
    private static readonly pb::MessageParser<RawFile> _parser = new pb::MessageParser<RawFile>(() => new RawFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RawFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nsys.Api.Ntypes.FileNtypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RawFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RawFile(RawFile other) : this() {
      data_ = other.data_;
      sha512256_ = other.sha512256_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RawFile Clone() {
      return new RawFile(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// The actual file data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sha512_256" field.</summary>
    public const int Sha512256FieldNumber = 2;
    private pb::ByteString sha512256_ = pb::ByteString.Empty;
    /// <summary>
    /// The 512/256 SHA sum for the data bytes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Sha512256 {
      get { return sha512256_; }
      set {
        sha512256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RawFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RawFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (Sha512256 != other.Sha512256) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Sha512256.Length != 0) hash ^= Sha512256.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (Sha512256.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Sha512256);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Sha512256.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha512256);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RawFile other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Sha512256.Length != 0) {
        Sha512256 = other.Sha512256;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 18: {
            Sha512256 = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GenericFile : pb::IMessage<GenericFile> {
    private static readonly pb::MessageParser<GenericFile> _parser = new pb::MessageParser<GenericFile>(() => new GenericFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GenericFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nsys.Api.Ntypes.FileNtypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericFile(GenericFile other) : this() {
      name_ = other.name_;
      description_ = other.description_;
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      originBasename_ = other.originBasename_;
      length_ = other.length_;
      rawFile_ = other.rawFile_ != null ? other.rawFile_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericFile Clone() {
      return new GenericFile(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The file's identifier which must be unique within the 
    /// account and must match the regex '^[0-9A-Za-z.-]{1,48}$'. 
    /// Automatically generated if not supplied in upload request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    /// <summary>
    /// For client or documented application use.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Any metadata_;
    /// <summary>
    /// For client or documented application use.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "origin_basename" field.</summary>
    public const int OriginBasenameFieldNumber = 4;
    private string originBasename_ = "";
    /// <summary>
    /// The basename of the file on the originating system, i.e., no
    /// directory path, no slashes -- the rightmost part of the name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OriginBasename {
      get { return originBasename_; }
      set {
        originBasename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 5;
    private uint length_;
    /// <summary>
    /// Length of the file in bytes. 
    /// Max length is always less than a gigabyte.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    /// <summary>Field number for the "raw_file" field.</summary>
    public const int RawFileFieldNumber = 6;
    private global::Nsys.Api.Ntypes.RawFile rawFile_;
    /// <summary>
    /// The actual file data and its checksum.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nsys.Api.Ntypes.RawFile RawFile {
      get { return rawFile_; }
      set {
        rawFile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GenericFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GenericFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (OriginBasename != other.OriginBasename) return false;
      if (Length != other.Length) return false;
      if (!object.Equals(RawFile, other.RawFile)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (OriginBasename.Length != 0) hash ^= OriginBasename.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (rawFile_ != null) hash ^= RawFile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (metadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Metadata);
      }
      if (OriginBasename.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OriginBasename);
      }
      if (Length != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Length);
      }
      if (rawFile_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(RawFile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (OriginBasename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginBasename);
      }
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Length);
      }
      if (rawFile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RawFile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GenericFile other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.OriginBasename.Length != 0) {
        OriginBasename = other.OriginBasename;
      }
      if (other.Length != 0) {
        Length = other.Length;
      }
      if (other.rawFile_ != null) {
        if (rawFile_ == null) {
          RawFile = new global::Nsys.Api.Ntypes.RawFile();
        }
        RawFile.MergeFrom(other.RawFile);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            if (metadata_ == null) {
              Metadata = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 34: {
            OriginBasename = input.ReadString();
            break;
          }
          case 40: {
            Length = input.ReadUInt32();
            break;
          }
          case 50: {
            if (rawFile_ == null) {
              RawFile = new global::Nsys.Api.Ntypes.RawFile();
            }
            input.ReadMessage(RawFile);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
