// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	ntypes "nsys.io/api/ntypes"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenderPdfResponse_Error int32

const (
	RenderPdfResponse_SUCCESS   RenderPdfResponse_Error = 0
	RenderPdfResponse_ENCRYPTED RenderPdfResponse_Error = 1
	RenderPdfResponse_CORRUPTED RenderPdfResponse_Error = 2
)

var RenderPdfResponse_Error_name = map[int32]string{
	0: "SUCCESS",
	1: "ENCRYPTED",
	2: "CORRUPTED",
}

var RenderPdfResponse_Error_value = map[string]int32{
	"SUCCESS":   0,
	"ENCRYPTED": 1,
	"CORRUPTED": 2,
}

func (x RenderPdfResponse_Error) String() string {
	return proto.EnumName(RenderPdfResponse_Error_name, int32(x))
}

func (RenderPdfResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{20, 0}
}

type ListResultsRequest struct {
	// Application-specific filter on returned results.
	// If not specified, all result listings are returned.
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResultsRequest) Reset()         { *m = ListResultsRequest{} }
func (m *ListResultsRequest) String() string { return proto.CompactTextString(m) }
func (*ListResultsRequest) ProtoMessage()    {}
func (*ListResultsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *ListResultsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResultsRequest.Unmarshal(m, b)
}
func (m *ListResultsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResultsRequest.Marshal(b, m, deterministic)
}
func (m *ListResultsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResultsRequest.Merge(m, src)
}
func (m *ListResultsRequest) XXX_Size() int {
	return xxx_messageInfo_ListResultsRequest.Size(m)
}
func (m *ListResultsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResultsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResultsRequest proto.InternalMessageInfo

func (m *ListResultsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListResultsResponse struct {
	AvailableResults     []*AvailableResult `protobuf:"bytes,1,rep,name=available_results,json=availableResults,proto3" json:"available_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResultsResponse) Reset()         { *m = ListResultsResponse{} }
func (m *ListResultsResponse) String() string { return proto.CompactTextString(m) }
func (*ListResultsResponse) ProtoMessage()    {}
func (*ListResultsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *ListResultsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResultsResponse.Unmarshal(m, b)
}
func (m *ListResultsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResultsResponse.Marshal(b, m, deterministic)
}
func (m *ListResultsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResultsResponse.Merge(m, src)
}
func (m *ListResultsResponse) XXX_Size() int {
	return xxx_messageInfo_ListResultsResponse.Size(m)
}
func (m *ListResultsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResultsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResultsResponse proto.InternalMessageInfo

func (m *ListResultsResponse) GetAvailableResults() []*AvailableResult {
	if m != nil {
		return m.AvailableResults
	}
	return nil
}

type AvailableResult struct {
	// The object's name / ID.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Application-specific meta information.
	Metadata             *any.Any `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableResult) Reset()         { *m = AvailableResult{} }
func (m *AvailableResult) String() string { return proto.CompactTextString(m) }
func (*AvailableResult) ProtoMessage()    {}
func (*AvailableResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *AvailableResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableResult.Unmarshal(m, b)
}
func (m *AvailableResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableResult.Marshal(b, m, deterministic)
}
func (m *AvailableResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableResult.Merge(m, src)
}
func (m *AvailableResult) XXX_Size() int {
	return xxx_messageInfo_AvailableResult.Size(m)
}
func (m *AvailableResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableResult.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableResult proto.InternalMessageInfo

func (m *AvailableResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AvailableResult) GetMetadata() *any.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetResultRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultRequest) Reset()         { *m = GetResultRequest{} }
func (m *GetResultRequest) String() string { return proto.CompactTextString(m) }
func (*GetResultRequest) ProtoMessage()    {}
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *GetResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultRequest.Unmarshal(m, b)
}
func (m *GetResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultRequest.Marshal(b, m, deterministic)
}
func (m *GetResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultRequest.Merge(m, src)
}
func (m *GetResultRequest) XXX_Size() int {
	return xxx_messageInfo_GetResultRequest.Size(m)
}
func (m *GetResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultRequest proto.InternalMessageInfo

func (m *GetResultRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResultResponse struct {
	// The result's ID.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The originating submission (the one specified to InitiateProcessing() which then
	// caused this result (and perhaps others) to be generated.
	OriginatingName string `protobuf:"bytes,2,opt,name=originating_name,json=originatingName,proto3" json:"originating_name,omitempty"`
	// Application-specific metadata (identical to that returned in results listings).
	Metadata *any.Any `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Contents of the returned file are application-specific.
	// The metadata within it does not necessarily have any relation to the metadata above.
	GenericFile          *ntypes.GenericFile `protobuf:"bytes,4,opt,name=generic_file,json=genericFile,proto3" json:"generic_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetResultResponse) Reset()         { *m = GetResultResponse{} }
func (m *GetResultResponse) String() string { return proto.CompactTextString(m) }
func (*GetResultResponse) ProtoMessage()    {}
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *GetResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultResponse.Unmarshal(m, b)
}
func (m *GetResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultResponse.Marshal(b, m, deterministic)
}
func (m *GetResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultResponse.Merge(m, src)
}
func (m *GetResultResponse) XXX_Size() int {
	return xxx_messageInfo_GetResultResponse.Size(m)
}
func (m *GetResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultResponse proto.InternalMessageInfo

func (m *GetResultResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResultResponse) GetOriginatingName() string {
	if m != nil {
		return m.OriginatingName
	}
	return ""
}

func (m *GetResultResponse) GetMetadata() *any.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetResultResponse) GetGenericFile() *ntypes.GenericFile {
	if m != nil {
		return m.GenericFile
	}
	return nil
}

type DeleteResultRequest struct {
	// The available result to delete.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResultRequest) Reset()         { *m = DeleteResultRequest{} }
func (m *DeleteResultRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteResultRequest) ProtoMessage()    {}
func (*DeleteResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *DeleteResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResultRequest.Unmarshal(m, b)
}
func (m *DeleteResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResultRequest.Marshal(b, m, deterministic)
}
func (m *DeleteResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResultRequest.Merge(m, src)
}
func (m *DeleteResultRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteResultRequest.Size(m)
}
func (m *DeleteResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResultRequest proto.InternalMessageInfo

func (m *DeleteResultRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UploadGenericFileRequest struct {
	// The file's identifier which must be unique within the
	// account and must match the regex '^[0-9A-Za-z.-]{1,48}$'.
	// Automatically generated if not supplied in upload request.
	Name        string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenericFile *ntypes.GenericFile `protobuf:"bytes,2,opt,name=generic_file,json=genericFile,proto3" json:"generic_file,omitempty"`
	// Requested file expiration time. The time is capped to comply with
	// account-specific minimums and maximums. A zero value requests the
	// maximum allowable expiration time be used.
	ExpireTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadGenericFileRequest) Reset()         { *m = UploadGenericFileRequest{} }
func (m *UploadGenericFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadGenericFileRequest) ProtoMessage()    {}
func (*UploadGenericFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{6}
}

func (m *UploadGenericFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadGenericFileRequest.Unmarshal(m, b)
}
func (m *UploadGenericFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadGenericFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadGenericFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadGenericFileRequest.Merge(m, src)
}
func (m *UploadGenericFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadGenericFileRequest.Size(m)
}
func (m *UploadGenericFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadGenericFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadGenericFileRequest proto.InternalMessageInfo

func (m *UploadGenericFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadGenericFileRequest) GetGenericFile() *ntypes.GenericFile {
	if m != nil {
		return m.GenericFile
	}
	return nil
}

func (m *UploadGenericFileRequest) GetExpireTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireTime
	}
	return nil
}

type UploadGenericFileResponse struct {
	// Identifier for the uploaded file.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// The actual expiration time for the file.
	ExpireTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadGenericFileResponse) Reset()         { *m = UploadGenericFileResponse{} }
func (m *UploadGenericFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadGenericFileResponse) ProtoMessage()    {}
func (*UploadGenericFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{7}
}

func (m *UploadGenericFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadGenericFileResponse.Unmarshal(m, b)
}
func (m *UploadGenericFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadGenericFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadGenericFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadGenericFileResponse.Merge(m, src)
}
func (m *UploadGenericFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadGenericFileResponse.Size(m)
}
func (m *UploadGenericFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadGenericFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadGenericFileResponse proto.InternalMessageInfo

func (m *UploadGenericFileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadGenericFileResponse) GetExpireTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireTime
	}
	return nil
}

type GetGenericFileRequest struct {
	// The generic file's identifier.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGenericFileRequest) Reset()         { *m = GetGenericFileRequest{} }
func (m *GetGenericFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetGenericFileRequest) ProtoMessage()    {}
func (*GetGenericFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{8}
}

func (m *GetGenericFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGenericFileRequest.Unmarshal(m, b)
}
func (m *GetGenericFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGenericFileRequest.Marshal(b, m, deterministic)
}
func (m *GetGenericFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGenericFileRequest.Merge(m, src)
}
func (m *GetGenericFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetGenericFileRequest.Size(m)
}
func (m *GetGenericFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGenericFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGenericFileRequest proto.InternalMessageInfo

func (m *GetGenericFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetGenericFileResponse struct {
	// The file's identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The actual file (SHA sum validated on the server side at read).
	GenericFile          *ntypes.GenericFile `protobuf:"bytes,2,opt,name=generic_file,json=genericFile,proto3" json:"generic_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetGenericFileResponse) Reset()         { *m = GetGenericFileResponse{} }
func (m *GetGenericFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetGenericFileResponse) ProtoMessage()    {}
func (*GetGenericFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{9}
}

func (m *GetGenericFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGenericFileResponse.Unmarshal(m, b)
}
func (m *GetGenericFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGenericFileResponse.Marshal(b, m, deterministic)
}
func (m *GetGenericFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGenericFileResponse.Merge(m, src)
}
func (m *GetGenericFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetGenericFileResponse.Size(m)
}
func (m *GetGenericFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGenericFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGenericFileResponse proto.InternalMessageInfo

func (m *GetGenericFileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGenericFileResponse) GetGenericFile() *ntypes.GenericFile {
	if m != nil {
		return m.GenericFile
	}
	return nil
}

type CreateFilesetRequest struct {
	// The fileset's identifier which must be unique within the
	// account and must match the regex '^[0-9A-Za-z.-]{1,48}$'.
	// Automatically generated if not supplied.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One or more files that are to become members of the fileset.
	FileNames []string `protobuf:"bytes,2,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	// Requested fileset expiration time. The time is capped so that it
	// is no later than the latest expiration time of any file in the set.
	// A zero value requests the maximum allowable expiration time be used.
	ExpireTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateFilesetRequest) Reset()         { *m = CreateFilesetRequest{} }
func (m *CreateFilesetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFilesetRequest) ProtoMessage()    {}
func (*CreateFilesetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{10}
}

func (m *CreateFilesetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFilesetRequest.Unmarshal(m, b)
}
func (m *CreateFilesetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFilesetRequest.Marshal(b, m, deterministic)
}
func (m *CreateFilesetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFilesetRequest.Merge(m, src)
}
func (m *CreateFilesetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFilesetRequest.Size(m)
}
func (m *CreateFilesetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFilesetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFilesetRequest proto.InternalMessageInfo

func (m *CreateFilesetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFilesetRequest) GetFileNames() []string {
	if m != nil {
		return m.FileNames
	}
	return nil
}

func (m *CreateFilesetRequest) GetExpireTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireTime
	}
	return nil
}

type CreateFilesetResponse struct {
	// Identifier for the fileset.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// The actual expiration time for the fileset.
	ExpireTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateFilesetResponse) Reset()         { *m = CreateFilesetResponse{} }
func (m *CreateFilesetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFilesetResponse) ProtoMessage()    {}
func (*CreateFilesetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{11}
}

func (m *CreateFilesetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFilesetResponse.Unmarshal(m, b)
}
func (m *CreateFilesetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFilesetResponse.Marshal(b, m, deterministic)
}
func (m *CreateFilesetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFilesetResponse.Merge(m, src)
}
func (m *CreateFilesetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFilesetResponse.Size(m)
}
func (m *CreateFilesetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFilesetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFilesetResponse proto.InternalMessageInfo

func (m *CreateFilesetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFilesetResponse) GetExpireTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireTime
	}
	return nil
}

type InitiateProcessingRequest struct {
	// Identifier of the object to process.
	// The context for interpretation of this identifier is set by the
	// client and application specific process code.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Application-specific type of processing to perform.
	ProcessCode          string   `protobuf:"bytes,2,opt,name=process_code,json=processCode,proto3" json:"process_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateProcessingRequest) Reset()         { *m = InitiateProcessingRequest{} }
func (m *InitiateProcessingRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateProcessingRequest) ProtoMessage()    {}
func (*InitiateProcessingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{12}
}

func (m *InitiateProcessingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateProcessingRequest.Unmarshal(m, b)
}
func (m *InitiateProcessingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateProcessingRequest.Marshal(b, m, deterministic)
}
func (m *InitiateProcessingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateProcessingRequest.Merge(m, src)
}
func (m *InitiateProcessingRequest) XXX_Size() int {
	return xxx_messageInfo_InitiateProcessingRequest.Size(m)
}
func (m *InitiateProcessingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateProcessingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateProcessingRequest proto.InternalMessageInfo

func (m *InitiateProcessingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitiateProcessingRequest) GetProcessCode() string {
	if m != nil {
		return m.ProcessCode
	}
	return ""
}

type DocToPdfRequest struct {
	// The generic file id of the document to be rendered.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocToPdfRequest) Reset()         { *m = DocToPdfRequest{} }
func (m *DocToPdfRequest) String() string { return proto.CompactTextString(m) }
func (*DocToPdfRequest) ProtoMessage()    {}
func (*DocToPdfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{13}
}

func (m *DocToPdfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocToPdfRequest.Unmarshal(m, b)
}
func (m *DocToPdfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocToPdfRequest.Marshal(b, m, deterministic)
}
func (m *DocToPdfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocToPdfRequest.Merge(m, src)
}
func (m *DocToPdfRequest) XXX_Size() int {
	return xxx_messageInfo_DocToPdfRequest.Size(m)
}
func (m *DocToPdfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocToPdfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocToPdfRequest proto.InternalMessageInfo

func (m *DocToPdfRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DocToPdfResponse struct {
	// the generic file id of the rendered pdf.
	PdfName              string   `protobuf:"bytes,1,opt,name=pdf_name,json=pdfName,proto3" json:"pdf_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocToPdfResponse) Reset()         { *m = DocToPdfResponse{} }
func (m *DocToPdfResponse) String() string { return proto.CompactTextString(m) }
func (*DocToPdfResponse) ProtoMessage()    {}
func (*DocToPdfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{14}
}

func (m *DocToPdfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocToPdfResponse.Unmarshal(m, b)
}
func (m *DocToPdfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocToPdfResponse.Marshal(b, m, deterministic)
}
func (m *DocToPdfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocToPdfResponse.Merge(m, src)
}
func (m *DocToPdfResponse) XXX_Size() int {
	return xxx_messageInfo_DocToPdfResponse.Size(m)
}
func (m *DocToPdfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocToPdfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocToPdfResponse proto.InternalMessageInfo

func (m *DocToPdfResponse) GetPdfName() string {
	if m != nil {
		return m.PdfName
	}
	return ""
}

type ParseEmailRequest struct {
	// The name of a generic file contaning an eml file
	EmlName string `protobuf:"bytes,1,opt,name=eml_name,json=emlName,proto3" json:"eml_name,omitempty"`
	// The whitelist of email attachment file extensions to save, things like:
	// ".pdf", ".png", ".tif", ".tiff", ".jpg", ".jpeg". If empty, then no
	// attachments will be saved. In any case a list of rejected attachments
	// will be returned.
	AttachmentWhitelist []string `protobuf:"bytes,2,rep,name=attachment_whitelist,json=attachmentWhitelist,proto3" json:"attachment_whitelist,omitempty"`
	// The whitelist of inline email attachment file extensions to save. If empty,
	// then no inline attachments will be saved.
	InlineWhitelist      []string `protobuf:"bytes,3,rep,name=inline_whitelist,json=inlineWhitelist,proto3" json:"inline_whitelist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseEmailRequest) Reset()         { *m = ParseEmailRequest{} }
func (m *ParseEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ParseEmailRequest) ProtoMessage()    {}
func (*ParseEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{15}
}

func (m *ParseEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseEmailRequest.Unmarshal(m, b)
}
func (m *ParseEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseEmailRequest.Marshal(b, m, deterministic)
}
func (m *ParseEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseEmailRequest.Merge(m, src)
}
func (m *ParseEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ParseEmailRequest.Size(m)
}
func (m *ParseEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseEmailRequest proto.InternalMessageInfo

func (m *ParseEmailRequest) GetEmlName() string {
	if m != nil {
		return m.EmlName
	}
	return ""
}

func (m *ParseEmailRequest) GetAttachmentWhitelist() []string {
	if m != nil {
		return m.AttachmentWhitelist
	}
	return nil
}

func (m *ParseEmailRequest) GetInlineWhitelist() []string {
	if m != nil {
		return m.InlineWhitelist
	}
	return nil
}

type ParseEmailResponse struct {
	// The name of a generic file containing the parsed email
	ParsedEmailName string `protobuf:"bytes,1,opt,name=parsed_email_name,json=parsedEmailName,proto3" json:"parsed_email_name,omitempty"`
	// The parsed email
	ParsedEmail          *ntypes.ParsedEmail `protobuf:"bytes,2,opt,name=parsed_email,json=parsedEmail,proto3" json:"parsed_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ParseEmailResponse) Reset()         { *m = ParseEmailResponse{} }
func (m *ParseEmailResponse) String() string { return proto.CompactTextString(m) }
func (*ParseEmailResponse) ProtoMessage()    {}
func (*ParseEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{16}
}

func (m *ParseEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseEmailResponse.Unmarshal(m, b)
}
func (m *ParseEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseEmailResponse.Marshal(b, m, deterministic)
}
func (m *ParseEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseEmailResponse.Merge(m, src)
}
func (m *ParseEmailResponse) XXX_Size() int {
	return xxx_messageInfo_ParseEmailResponse.Size(m)
}
func (m *ParseEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseEmailResponse proto.InternalMessageInfo

func (m *ParseEmailResponse) GetParsedEmailName() string {
	if m != nil {
		return m.ParsedEmailName
	}
	return ""
}

func (m *ParseEmailResponse) GetParsedEmail() *ntypes.ParsedEmail {
	if m != nil {
		return m.ParsedEmail
	}
	return nil
}

type RenderEmailBodyRequest struct {
	// The name of a generic file contaning an eml file
	EmlName string `protobuf:"bytes,1,opt,name=eml_name,json=emlName,proto3" json:"eml_name,omitempty"`
	// The whitelist of inline email attachments to include in the rendering,
	// things like: ".jpg", ".jpeg", ".png", ".gif". If empty, then no inline
	// attachments will be rendered in the email body.
	InlineAttachmentWhitelist []string `protobuf:"bytes,2,rep,name=inline_attachment_whitelist,json=inlineAttachmentWhitelist,proto3" json:"inline_attachment_whitelist,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *RenderEmailBodyRequest) Reset()         { *m = RenderEmailBodyRequest{} }
func (m *RenderEmailBodyRequest) String() string { return proto.CompactTextString(m) }
func (*RenderEmailBodyRequest) ProtoMessage()    {}
func (*RenderEmailBodyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{17}
}

func (m *RenderEmailBodyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderEmailBodyRequest.Unmarshal(m, b)
}
func (m *RenderEmailBodyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderEmailBodyRequest.Marshal(b, m, deterministic)
}
func (m *RenderEmailBodyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderEmailBodyRequest.Merge(m, src)
}
func (m *RenderEmailBodyRequest) XXX_Size() int {
	return xxx_messageInfo_RenderEmailBodyRequest.Size(m)
}
func (m *RenderEmailBodyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderEmailBodyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderEmailBodyRequest proto.InternalMessageInfo

func (m *RenderEmailBodyRequest) GetEmlName() string {
	if m != nil {
		return m.EmlName
	}
	return ""
}

func (m *RenderEmailBodyRequest) GetInlineAttachmentWhitelist() []string {
	if m != nil {
		return m.InlineAttachmentWhitelist
	}
	return nil
}

type RenderEmailBodyResponse struct {
	// The generic file ID of the rendered email pdf
	EmailPdfName         string   `protobuf:"bytes,1,opt,name=email_pdf_name,json=emailPdfName,proto3" json:"email_pdf_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderEmailBodyResponse) Reset()         { *m = RenderEmailBodyResponse{} }
func (m *RenderEmailBodyResponse) String() string { return proto.CompactTextString(m) }
func (*RenderEmailBodyResponse) ProtoMessage()    {}
func (*RenderEmailBodyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{18}
}

func (m *RenderEmailBodyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderEmailBodyResponse.Unmarshal(m, b)
}
func (m *RenderEmailBodyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderEmailBodyResponse.Marshal(b, m, deterministic)
}
func (m *RenderEmailBodyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderEmailBodyResponse.Merge(m, src)
}
func (m *RenderEmailBodyResponse) XXX_Size() int {
	return xxx_messageInfo_RenderEmailBodyResponse.Size(m)
}
func (m *RenderEmailBodyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderEmailBodyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderEmailBodyResponse proto.InternalMessageInfo

func (m *RenderEmailBodyResponse) GetEmailPdfName() string {
	if m != nil {
		return m.EmailPdfName
	}
	return ""
}

type RenderPdfRequest struct {
	// The name of a generic file containing a pdf file
	PdfName              string   `protobuf:"bytes,1,opt,name=pdf_name,json=pdfName,proto3" json:"pdf_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderPdfRequest) Reset()         { *m = RenderPdfRequest{} }
func (m *RenderPdfRequest) String() string { return proto.CompactTextString(m) }
func (*RenderPdfRequest) ProtoMessage()    {}
func (*RenderPdfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{19}
}

func (m *RenderPdfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderPdfRequest.Unmarshal(m, b)
}
func (m *RenderPdfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderPdfRequest.Marshal(b, m, deterministic)
}
func (m *RenderPdfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderPdfRequest.Merge(m, src)
}
func (m *RenderPdfRequest) XXX_Size() int {
	return xxx_messageInfo_RenderPdfRequest.Size(m)
}
func (m *RenderPdfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderPdfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderPdfRequest proto.InternalMessageInfo

func (m *RenderPdfRequest) GetPdfName() string {
	if m != nil {
		return m.PdfName
	}
	return ""
}

type RenderPdfResponse struct {
	// The generic file IDs of the rendered pages
	PageNames            []string                `protobuf:"bytes,1,rep,name=page_names,json=pageNames,proto3" json:"page_names,omitempty"`
	Error                RenderPdfResponse_Error `protobuf:"varint,2,opt,name=error,proto3,enum=nsys.api.file.RenderPdfResponse_Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RenderPdfResponse) Reset()         { *m = RenderPdfResponse{} }
func (m *RenderPdfResponse) String() string { return proto.CompactTextString(m) }
func (*RenderPdfResponse) ProtoMessage()    {}
func (*RenderPdfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{20}
}

func (m *RenderPdfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderPdfResponse.Unmarshal(m, b)
}
func (m *RenderPdfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderPdfResponse.Marshal(b, m, deterministic)
}
func (m *RenderPdfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderPdfResponse.Merge(m, src)
}
func (m *RenderPdfResponse) XXX_Size() int {
	return xxx_messageInfo_RenderPdfResponse.Size(m)
}
func (m *RenderPdfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderPdfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderPdfResponse proto.InternalMessageInfo

func (m *RenderPdfResponse) GetPageNames() []string {
	if m != nil {
		return m.PageNames
	}
	return nil
}

func (m *RenderPdfResponse) GetError() RenderPdfResponse_Error {
	if m != nil {
		return m.Error
	}
	return RenderPdfResponse_SUCCESS
}

type SplitTiffRequest struct {
	// The name of a generic file containing a tiff file
	TiffName             string   `protobuf:"bytes,1,opt,name=tiff_name,json=tiffName,proto3" json:"tiff_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitTiffRequest) Reset()         { *m = SplitTiffRequest{} }
func (m *SplitTiffRequest) String() string { return proto.CompactTextString(m) }
func (*SplitTiffRequest) ProtoMessage()    {}
func (*SplitTiffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{21}
}

func (m *SplitTiffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitTiffRequest.Unmarshal(m, b)
}
func (m *SplitTiffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitTiffRequest.Marshal(b, m, deterministic)
}
func (m *SplitTiffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitTiffRequest.Merge(m, src)
}
func (m *SplitTiffRequest) XXX_Size() int {
	return xxx_messageInfo_SplitTiffRequest.Size(m)
}
func (m *SplitTiffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitTiffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SplitTiffRequest proto.InternalMessageInfo

func (m *SplitTiffRequest) GetTiffName() string {
	if m != nil {
		return m.TiffName
	}
	return ""
}

type SplitTiffResponse struct {
	// The generic file IDs of the individual pages
	PageNames            []string `protobuf:"bytes,1,rep,name=page_names,json=pageNames,proto3" json:"page_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitTiffResponse) Reset()         { *m = SplitTiffResponse{} }
func (m *SplitTiffResponse) String() string { return proto.CompactTextString(m) }
func (*SplitTiffResponse) ProtoMessage()    {}
func (*SplitTiffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{22}
}

func (m *SplitTiffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitTiffResponse.Unmarshal(m, b)
}
func (m *SplitTiffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitTiffResponse.Marshal(b, m, deterministic)
}
func (m *SplitTiffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitTiffResponse.Merge(m, src)
}
func (m *SplitTiffResponse) XXX_Size() int {
	return xxx_messageInfo_SplitTiffResponse.Size(m)
}
func (m *SplitTiffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitTiffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SplitTiffResponse proto.InternalMessageInfo

func (m *SplitTiffResponse) GetPageNames() []string {
	if m != nil {
		return m.PageNames
	}
	return nil
}

func init() {
	proto.RegisterEnum("nsys.api.file.RenderPdfResponse_Error", RenderPdfResponse_Error_name, RenderPdfResponse_Error_value)
	proto.RegisterType((*ListResultsRequest)(nil), "nsys.api.file.ListResultsRequest")
	proto.RegisterType((*ListResultsResponse)(nil), "nsys.api.file.ListResultsResponse")
	proto.RegisterType((*AvailableResult)(nil), "nsys.api.file.AvailableResult")
	proto.RegisterType((*GetResultRequest)(nil), "nsys.api.file.GetResultRequest")
	proto.RegisterType((*GetResultResponse)(nil), "nsys.api.file.GetResultResponse")
	proto.RegisterType((*DeleteResultRequest)(nil), "nsys.api.file.DeleteResultRequest")
	proto.RegisterType((*UploadGenericFileRequest)(nil), "nsys.api.file.UploadGenericFileRequest")
	proto.RegisterType((*UploadGenericFileResponse)(nil), "nsys.api.file.UploadGenericFileResponse")
	proto.RegisterType((*GetGenericFileRequest)(nil), "nsys.api.file.GetGenericFileRequest")
	proto.RegisterType((*GetGenericFileResponse)(nil), "nsys.api.file.GetGenericFileResponse")
	proto.RegisterType((*CreateFilesetRequest)(nil), "nsys.api.file.CreateFilesetRequest")
	proto.RegisterType((*CreateFilesetResponse)(nil), "nsys.api.file.CreateFilesetResponse")
	proto.RegisterType((*InitiateProcessingRequest)(nil), "nsys.api.file.InitiateProcessingRequest")
	proto.RegisterType((*DocToPdfRequest)(nil), "nsys.api.file.DocToPdfRequest")
	proto.RegisterType((*DocToPdfResponse)(nil), "nsys.api.file.DocToPdfResponse")
	proto.RegisterType((*ParseEmailRequest)(nil), "nsys.api.file.ParseEmailRequest")
	proto.RegisterType((*ParseEmailResponse)(nil), "nsys.api.file.ParseEmailResponse")
	proto.RegisterType((*RenderEmailBodyRequest)(nil), "nsys.api.file.RenderEmailBodyRequest")
	proto.RegisterType((*RenderEmailBodyResponse)(nil), "nsys.api.file.RenderEmailBodyResponse")
	proto.RegisterType((*RenderPdfRequest)(nil), "nsys.api.file.RenderPdfRequest")
	proto.RegisterType((*RenderPdfResponse)(nil), "nsys.api.file.RenderPdfResponse")
	proto.RegisterType((*SplitTiffRequest)(nil), "nsys.api.file.SplitTiffRequest")
	proto.RegisterType((*SplitTiffResponse)(nil), "nsys.api.file.SplitTiffResponse")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 1206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x72, 0xe3, 0x34,
	0x14, 0xae, 0xd3, 0xfd, 0x69, 0x4e, 0xda, 0xc6, 0xd1, 0xb6, 0x25, 0x71, 0x29, 0xcd, 0x7a, 0xdb,
	0xd2, 0x05, 0x36, 0x81, 0x70, 0x09, 0xc3, 0x4e, 0x37, 0x0d, 0x1d, 0x86, 0xd2, 0x66, 0xdc, 0x76,
	0x77, 0xd9, 0xd9, 0x99, 0xa0, 0x34, 0x4a, 0xaa, 0x19, 0xc7, 0x36, 0xb6, 0x0a, 0xf4, 0x92, 0x1b,
	0xae, 0x78, 0x0c, 0x2e, 0x79, 0x0d, 0x1e, 0x82, 0xb7, 0x61, 0x64, 0xd9, 0x8e, 0x23, 0x25, 0xb1,
	0x77, 0x76, 0xb8, 0x8b, 0xce, 0xf9, 0x74, 0xf4, 0x9d, 0x4f, 0xd2, 0x39, 0x56, 0x00, 0x86, 0xd4,
	0x26, 0x0d, 0xcf, 0x77, 0x99, 0x8b, 0xd6, 0x9c, 0xe0, 0x2e, 0x68, 0x60, 0x8f, 0x36, 0xb8, 0xd1,
	0x78, 0x32, 0x72, 0xdd, 0x91, 0x4d, 0x9a, 0xb6, 0xeb, 0x8c, 0xfc, 0x5b, 0xc7, 0xa1, 0xce, 0xa8,
	0xe9, 0x7a, 0xc4, 0xc7, 0x8c, 0xba, 0x4e, 0x20, 0xe6, 0x18, 0xbb, 0x11, 0x28, 0x1c, 0xf5, 0x6f,
	0x87, 0x4d, 0x46, 0xc7, 0x24, 0x60, 0x78, 0xec, 0x45, 0x80, 0x6d, 0x19, 0x40, 0xc6, 0x1e, 0xbb,
	0x8b, 0x9c, 0x35, 0xd9, 0x89, 0x9d, 0xd8, 0xb5, 0x17, 0x92, 0xa1, 0x6e, 0x13, 0x7b, 0xb4, 0xe9,
	0xb0, 0x3b, 0x8f, 0x04, 0x4d, 0x4e, 0xab, 0x27, 0x7e, 0x0b, 0x94, 0xf9, 0x19, 0xa0, 0x53, 0x1a,
	0x30, 0x8b, 0x04, 0xb7, 0x36, 0x0b, 0x2c, 0xf2, 0xf3, 0x2d, 0x09, 0x18, 0xda, 0x82, 0x07, 0x43,
	0x6a, 0x33, 0xe2, 0x57, 0xb5, 0xba, 0x76, 0x58, 0xb4, 0xa2, 0x91, 0xd9, 0x87, 0x47, 0x53, 0xe8,
	0xc0, 0x73, 0x9d, 0x80, 0xa0, 0xef, 0xa1, 0x82, 0x7f, 0xc1, 0xd4, 0xc6, 0x7d, 0x9b, 0xf4, 0x7c,
	0xe1, 0xac, 0x6a, 0xf5, 0xe5, 0xc3, 0x52, 0xeb, 0xa3, 0xc6, 0x94, 0x26, 0x8d, 0xa3, 0x18, 0x27,
	0x62, 0x58, 0x3a, 0x9e, 0x36, 0x04, 0xe6, 0x2b, 0x28, 0x4b, 0x20, 0x84, 0xe0, 0x9e, 0x83, 0xc7,
	0x24, 0x22, 0x13, 0xfe, 0x46, 0x9f, 0xc3, 0xca, 0x98, 0x30, 0x3c, 0xc0, 0x0c, 0x57, 0x0b, 0x75,
	0xed, 0xb0, 0xd4, 0xda, 0x68, 0x08, 0x31, 0x1a, 0xb1, 0x18, 0x8d, 0x23, 0xe7, 0xce, 0x4a, 0x50,
	0xe6, 0x01, 0xe8, 0x27, 0x24, 0xe2, 0x1e, 0x27, 0x3a, 0x23, 0xb2, 0xf9, 0x8f, 0x06, 0x95, 0x14,
	0x30, 0xca, 0x71, 0x16, 0x87, 0xa7, 0xa0, 0xbb, 0x3e, 0x1d, 0x51, 0x07, 0x33, 0xea, 0x8c, 0x7a,
	0xa1, 0xbf, 0x10, 0xfa, 0xcb, 0x29, 0xfb, 0x99, 0x4c, 0x77, 0x39, 0x0f, 0x5d, 0xf4, 0x1c, 0x56,
	0x47, 0xc4, 0x21, 0x3e, 0xbd, 0xee, 0x71, 0xe5, 0xaa, 0xf7, 0xc2, 0x59, 0x1f, 0x4e, 0xf4, 0x8c,
	0xf6, 0xf1, 0x44, 0x80, 0xbe, 0xa5, 0x36, 0xb1, 0x4a, 0xa3, 0xc9, 0xc0, 0x7c, 0x0a, 0x8f, 0x8e,
	0x89, 0x4d, 0x18, 0xc9, 0x4e, 0xf9, 0x6f, 0x0d, 0xaa, 0x57, 0x9e, 0xed, 0xe2, 0x41, 0x3a, 0xda,
	0xfc, 0x09, 0x0a, 0xb9, 0xc2, 0x3b, 0x92, 0x43, 0x5f, 0x41, 0x89, 0xfc, 0xe6, 0x51, 0x9f, 0xf4,
	0xf8, 0x79, 0x8f, 0x24, 0x31, 0x14, 0x49, 0x2e, 0xe3, 0xcb, 0x60, 0x81, 0x80, 0x73, 0x83, 0x69,
	0x43, 0x6d, 0x06, 0xdb, 0xc9, 0x46, 0x9d, 0xa5, 0xe8, 0x86, 0xea, 0x4b, 0xab, 0x15, 0xde, 0x69,
	0xb5, 0x4f, 0x61, 0xf3, 0x84, 0xb0, 0x7c, 0xc2, 0x98, 0x63, 0xd8, 0x92, 0xc1, 0x0b, 0x0e, 0xd0,
	0xfb, 0xca, 0x68, 0xfe, 0xa1, 0xc1, 0x46, 0xdb, 0x27, 0x98, 0x11, 0x3e, 0x0c, 0xc8, 0xa2, 0x5d,
	0x46, 0x3b, 0xa2, 0x58, 0x85, 0xe7, 0x34, 0xa8, 0x16, 0xea, 0xcb, 0x87, 0x45, 0xab, 0xc8, 0x2d,
	0x5c, 0xa3, 0xe0, 0xfd, 0xb6, 0xe4, 0x06, 0x36, 0x25, 0x1e, 0xff, 0xd7, 0x76, 0x58, 0x50, 0xfb,
	0xce, 0xa1, 0x8c, 0x62, 0x46, 0xba, 0xbe, 0x7b, 0x4d, 0x82, 0x80, 0x3a, 0xa3, 0x45, 0x69, 0x3f,
	0x86, 0x55, 0x4f, 0x00, 0x7b, 0xd7, 0xee, 0x20, 0xbe, 0xa1, 0xa5, 0xc8, 0xd6, 0x76, 0x07, 0xc4,
	0xdc, 0x87, 0xf2, 0xb1, 0x7b, 0x7d, 0xe9, 0x76, 0x07, 0xc3, 0x45, 0x9b, 0xfb, 0x0c, 0xf4, 0x09,
	0x2c, 0xca, 0xaf, 0x06, 0x2b, 0xde, 0x60, 0xd8, 0x4b, 0x61, 0x1f, 0x7a, 0x83, 0x21, 0x4f, 0xd3,
	0xfc, 0x53, 0x83, 0x4a, 0x17, 0xfb, 0x01, 0xe9, 0x8c, 0x31, 0xb5, 0xe3, 0xc0, 0x35, 0x58, 0x21,
	0x63, 0x7b, 0x6a, 0x02, 0x19, 0xdb, 0xa1, 0x2e, 0x5f, 0xc0, 0x06, 0x66, 0x0c, 0x5f, 0xdf, 0x8c,
	0x89, 0xc3, 0x7a, 0xbf, 0xde, 0x50, 0x46, 0x6c, 0x1a, 0xb0, 0x68, 0xab, 0x1e, 0x4d, 0x7c, 0xaf,
	0x62, 0x17, 0x2f, 0x41, 0xd4, 0xb1, 0xa9, 0x43, 0x52, 0xf0, 0xe5, 0x10, 0x5e, 0x16, 0xf6, 0x04,
	0x6a, 0xfe, 0xae, 0x01, 0x4a, 0xd3, 0x89, 0x12, 0xf8, 0x04, 0x2a, 0x1e, 0xb7, 0x0e, 0x7a, 0x84,
	0xdb, 0xd3, 0xc4, 0xca, 0xc2, 0x11, 0xe2, 0xcf, 0xa2, 0xf3, 0x9a, 0xc6, 0xce, 0x3d, 0xaf, 0xdd,
	0xc9, 0x3c, 0xab, 0x94, 0x0a, 0x62, 0x06, 0xb0, 0x65, 0x11, 0x67, 0x40, 0xfc, 0x70, 0xf8, 0xc2,
	0x1d, 0xdc, 0xe5, 0x90, 0xe5, 0x1b, 0xd8, 0x8e, 0x72, 0x5c, 0xa0, 0x4e, 0x4d, 0x40, 0x8e, 0x54,
	0x8d, 0xcc, 0xe7, 0xf0, 0x81, 0xb2, 0x68, 0x94, 0xfc, 0x1e, 0xac, 0x8b, 0xac, 0xa5, 0x3d, 0x5c,
	0x0d, 0xad, 0xdd, 0x68, 0x23, 0x9f, 0x81, 0x2e, 0x02, 0xa4, 0xce, 0xc7, 0x82, 0x7d, 0xff, 0x4b,
	0x83, 0x4a, 0x0a, 0x1f, 0x2d, 0xb5, 0x03, 0xe0, 0xe1, 0x51, 0x7c, 0xfb, 0x34, 0x71, 0xfb, 0xb8,
	0x45, 0xdc, 0xbe, 0xaf, 0xe1, 0x3e, 0xf1, 0x7d, 0xd7, 0x0f, 0x35, 0x5d, 0x6f, 0x1d, 0x48, 0x7d,
	0x53, 0x89, 0xd7, 0xe8, 0x70, 0xb4, 0x25, 0x26, 0x99, 0x2d, 0xb8, 0x1f, 0x8e, 0x51, 0x09, 0x1e,
	0x5e, 0x5c, 0xb5, 0xdb, 0x9d, 0x8b, 0x0b, 0x7d, 0x09, 0xad, 0x41, 0xb1, 0x73, 0xd6, 0xb6, 0x7e,
	0xec, 0x5e, 0x76, 0x8e, 0x75, 0x8d, 0x0f, 0xdb, 0xe7, 0x96, 0x75, 0x15, 0x0e, 0x0b, 0x66, 0x13,
	0xf4, 0x0b, 0xcf, 0xa6, 0xec, 0x92, 0x0e, 0x93, 0xac, 0xb6, 0xa1, 0xc8, 0xe8, 0x70, 0x2a, 0xad,
	0x15, 0x6e, 0x08, 0xf3, 0x6a, 0x41, 0x25, 0x35, 0x21, 0x57, 0x5a, 0xad, 0x7f, 0x75, 0x58, 0xe7,
	0x25, 0x61, 0x72, 0x55, 0xd1, 0x0d, 0x54, 0x94, 0xea, 0x8d, 0x3e, 0x96, 0xf2, 0x9d, 0xd7, 0x8d,
	0x8c, 0xc3, 0x6c, 0xa0, 0x60, 0x66, 0x2e, 0xa1, 0x9f, 0x60, 0x43, 0x71, 0x9f, 0x5a, 0xe7, 0xf9,
	0x17, 0xdb, 0x89, 0x6b, 0x52, 0xea, 0x13, 0xae, 0x71, 0x1e, 0x7f, 0xc2, 0x99, 0x4b, 0xa8, 0x07,
	0xeb, 0xd3, 0xe5, 0x1e, 0xed, 0x49, 0xb1, 0x67, 0xb6, 0x0e, 0x63, 0x3f, 0x03, 0x95, 0xa4, 0xf0,
	0x26, 0xfc, 0x16, 0x91, 0xf8, 0xe7, 0x5b, 0x23, 0x93, 0xfc, 0x5b, 0x58, 0x9b, 0xaa, 0xd9, 0xe8,
	0x89, 0x14, 0x77, 0x56, 0x67, 0x31, 0xf6, 0x16, 0x83, 0x12, 0xe6, 0xaf, 0x41, 0x9f, 0x72, 0x71,
	0xe2, 0xb9, 0x16, 0xc8, 0xe4, 0xfd, 0x1a, 0x90, 0xda, 0x01, 0x90, 0x7c, 0x30, 0xe6, 0x36, 0x09,
	0x63, 0x4b, 0xe9, 0x34, 0x1d, 0xfe, 0x49, 0x6d, 0x2e, 0xa1, 0x3e, 0x6c, 0xaa, 0xd3, 0x38, 0xf1,
	0xfc, 0xc1, 0x33, 0xd9, 0xff, 0x00, 0x2b, 0x71, 0x13, 0x41, 0xf2, 0xd7, 0xb1, 0xd4, 0x84, 0x8c,
	0xdd, 0xb9, 0xfe, 0x44, 0xe6, 0x33, 0x28, 0xc5, 0x56, 0x4e, 0x34, 0x2b, 0x62, 0x26, 0xbd, 0x0b,
	0x80, 0x49, 0x93, 0x40, 0x75, 0x29, 0x9c, 0xd2, 0xce, 0x8c, 0xc7, 0x0b, 0x10, 0x09, 0x49, 0x0b,
	0xd6, 0x26, 0x76, 0x4e, 0x33, 0x3b, 0x6e, 0x26, 0xd1, 0x3e, 0x94, 0xa5, 0xaa, 0x8e, 0xf6, 0x67,
	0x16, 0x4d, 0xb9, 0xd5, 0x18, 0x07, 0x59, 0xb0, 0x84, 0xf7, 0x5b, 0x40, 0x92, 0x93, 0x93, 0xcf,
	0xb9, 0x4c, 0x66, 0x06, 0x5d, 0x28, 0x26, 0x65, 0x1d, 0xed, 0xce, 0x2f, 0xf8, 0x22, 0x5c, 0x3d,
	0xab, 0x23, 0x84, 0x11, 0x57, 0x13, 0x33, 0x67, 0x9a, 0x19, 0x34, 0x0f, 0xc7, 0xa4, 0xe6, 0x2b,
	0xe1, 0xe4, 0xf6, 0xa1, 0x70, 0x54, 0xda, 0x85, 0xe0, 0x98, 0x98, 0x67, 0x71, 0x54, 0x82, 0x66,
	0x72, 0x7c, 0x09, 0xa5, 0xd4, 0xab, 0x14, 0xc9, 0x27, 0x52, 0x7d, 0xdf, 0x1a, 0xe6, 0x22, 0x48,
	0xc2, 0xf4, 0x12, 0xd6, 0x53, 0x0e, 0xce, 0x35, 0x47, 0xe8, 0x3c, 0x8a, 0x26, 0xaf, 0x4b, 0x25,
	0x79, 0xf9, 0x81, 0xaa, 0x28, 0xaa, 0x3c, 0x4c, 0x85, 0xa2, 0x89, 0x79, 0x96, 0xa2, 0x4a, 0xd0,
	0x4c, 0x8e, 0xa7, 0xb0, 0x9a, 0x7e, 0x3a, 0x22, 0x59, 0xaf, 0x19, 0xef, 0xca, 0x05, 0x55, 0xf5,
	0x25, 0x94, 0xd3, 0x13, 0x38, 0xc5, 0x3c, 0x01, 0xb3, 0x58, 0xbe, 0x40, 0x6f, 0xf4, 0xf4, 0x7f,
	0x1c, 0x3c, 0x50, 0xff, 0x41, 0xb8, 0xfa, 0x97, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x36, 0x11,
	0xf1, 0x37, 0x97, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileProcessingClient is the client API for FileProcessing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileProcessingClient interface {
	// Upload a generic file for further processing later.
	UploadGenericFile(ctx context.Context, in *UploadGenericFileRequest, opts ...grpc.CallOption) (*UploadGenericFileResponse, error)
	UploadGenericFileLRO(ctx context.Context, in *UploadGenericFileRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Download a previously uploaded generic file.
	GetGenericFile(ctx context.Context, in *GetGenericFileRequest, opts ...grpc.CallOption) (*GetGenericFileResponse, error)
	GetGenericFileLRO(ctx context.Context, in *GetGenericFileRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Group any number of previously-uploaded files together into a
	// single fileset. Files may have membership in multiple filesets.
	CreateFileset(ctx context.Context, in *CreateFilesetRequest, opts ...grpc.CallOption) (*CreateFilesetResponse, error)
	CreateFilesetLRO(ctx context.Context, in *CreateFilesetRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Begin processing a file or fileset in the specified way.
	// This is a temporary hack (therefore this will be here forever ;-)
	// The results of the processing are obtained by polling for them
	// using the ListResults() RPC and fetching via GetResult().
	InitiateProcessing(ctx context.Context, in *InitiateProcessingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	InitiateProcessingLRO(ctx context.Context, in *InitiateProcessingRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Given a document (.doc, .docx, .txt, .ppt, ect.) convert it to pdf
	DocToPdf(ctx context.Context, in *DocToPdfRequest, opts ...grpc.CallOption) (*DocToPdfResponse, error)
	DocToPdfLRO(ctx context.Context, in *DocToPdfRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Parses an email *.eml file stored as a generic file. Stores all
	// attachments as new generic files and returns the email headers, body,
	// and list of attachments.
	ParseEmail(ctx context.Context, in *ParseEmailRequest, opts ...grpc.CallOption) (*ParseEmailResponse, error)
	ParseEmailLRO(ctx context.Context, in *ParseEmailRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Given an email *.eml file stored as a generic file, this renders the
	// email body as a pdf and stores the pdf as a new generic file.
	RenderEmailBody(ctx context.Context, in *RenderEmailBodyRequest, opts ...grpc.CallOption) (*RenderEmailBodyResponse, error)
	RenderEmailBodyLRO(ctx context.Context, in *RenderEmailBodyRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Given a pdf file stored as a generic file, this renders the individual
	// pages of the pdf as png files and stores them as new generic files. It
	// will render them at 300 DPI.
	RenderPdf(ctx context.Context, in *RenderPdfRequest, opts ...grpc.CallOption) (*RenderPdfResponse, error)
	RenderPdfLRO(ctx context.Context, in *RenderPdfRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Given a tiff file stored as a generic file, this splits the pages into
	// individual png files and stores them as new generic files.
	SplitTiff(ctx context.Context, in *SplitTiffRequest, opts ...grpc.CallOption) (*SplitTiffResponse, error)
	SplitTiffLRO(ctx context.Context, in *SplitTiffRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Returns a list of available processed results (i.e., the final outputs
	// of the client/application-specific operations triggered by InitiateProcessing()
	ListResults(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*ListResultsResponse, error)
	ListResultsLRO(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Fetch any available result.
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	GetResultLRO(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Delete any available result.
	DeleteResult(ctx context.Context, in *DeleteResultRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteResultLRO(ctx context.Context, in *DeleteResultRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
}

type fileProcessingClient struct {
	cc *grpc.ClientConn
}

func NewFileProcessingClient(cc *grpc.ClientConn) FileProcessingClient {
	return &fileProcessingClient{cc}
}

func (c *fileProcessingClient) UploadGenericFile(ctx context.Context, in *UploadGenericFileRequest, opts ...grpc.CallOption) (*UploadGenericFileResponse, error) {
	out := new(UploadGenericFileResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/UploadGenericFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) UploadGenericFileLRO(ctx context.Context, in *UploadGenericFileRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/UploadGenericFileLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) GetGenericFile(ctx context.Context, in *GetGenericFileRequest, opts ...grpc.CallOption) (*GetGenericFileResponse, error) {
	out := new(GetGenericFileResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/GetGenericFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) GetGenericFileLRO(ctx context.Context, in *GetGenericFileRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/GetGenericFileLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) CreateFileset(ctx context.Context, in *CreateFilesetRequest, opts ...grpc.CallOption) (*CreateFilesetResponse, error) {
	out := new(CreateFilesetResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/CreateFileset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) CreateFilesetLRO(ctx context.Context, in *CreateFilesetRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/CreateFilesetLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) InitiateProcessing(ctx context.Context, in *InitiateProcessingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/InitiateProcessing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) InitiateProcessingLRO(ctx context.Context, in *InitiateProcessingRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/InitiateProcessingLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) DocToPdf(ctx context.Context, in *DocToPdfRequest, opts ...grpc.CallOption) (*DocToPdfResponse, error) {
	out := new(DocToPdfResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/DocToPdf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) DocToPdfLRO(ctx context.Context, in *DocToPdfRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/DocToPdfLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) ParseEmail(ctx context.Context, in *ParseEmailRequest, opts ...grpc.CallOption) (*ParseEmailResponse, error) {
	out := new(ParseEmailResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/ParseEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) ParseEmailLRO(ctx context.Context, in *ParseEmailRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/ParseEmailLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) RenderEmailBody(ctx context.Context, in *RenderEmailBodyRequest, opts ...grpc.CallOption) (*RenderEmailBodyResponse, error) {
	out := new(RenderEmailBodyResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/RenderEmailBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) RenderEmailBodyLRO(ctx context.Context, in *RenderEmailBodyRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/RenderEmailBodyLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) RenderPdf(ctx context.Context, in *RenderPdfRequest, opts ...grpc.CallOption) (*RenderPdfResponse, error) {
	out := new(RenderPdfResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/RenderPdf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) RenderPdfLRO(ctx context.Context, in *RenderPdfRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/RenderPdfLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) SplitTiff(ctx context.Context, in *SplitTiffRequest, opts ...grpc.CallOption) (*SplitTiffResponse, error) {
	out := new(SplitTiffResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/SplitTiff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) SplitTiffLRO(ctx context.Context, in *SplitTiffRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/SplitTiffLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) ListResults(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*ListResultsResponse, error) {
	out := new(ListResultsResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/ListResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) ListResultsLRO(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/ListResultsLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/GetResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) GetResultLRO(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/GetResultLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) DeleteResult(ctx context.Context, in *DeleteResultRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/DeleteResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessingClient) DeleteResultLRO(ctx context.Context, in *DeleteResultRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/nsys.api.file.FileProcessing/DeleteResultLRO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileProcessingServer is the server API for FileProcessing service.
type FileProcessingServer interface {
	// Upload a generic file for further processing later.
	UploadGenericFile(context.Context, *UploadGenericFileRequest) (*UploadGenericFileResponse, error)
	UploadGenericFileLRO(context.Context, *UploadGenericFileRequest) (*longrunning.Operation, error)
	// Download a previously uploaded generic file.
	GetGenericFile(context.Context, *GetGenericFileRequest) (*GetGenericFileResponse, error)
	GetGenericFileLRO(context.Context, *GetGenericFileRequest) (*longrunning.Operation, error)
	// Group any number of previously-uploaded files together into a
	// single fileset. Files may have membership in multiple filesets.
	CreateFileset(context.Context, *CreateFilesetRequest) (*CreateFilesetResponse, error)
	CreateFilesetLRO(context.Context, *CreateFilesetRequest) (*longrunning.Operation, error)
	// Begin processing a file or fileset in the specified way.
	// This is a temporary hack (therefore this will be here forever ;-)
	// The results of the processing are obtained by polling for them
	// using the ListResults() RPC and fetching via GetResult().
	InitiateProcessing(context.Context, *InitiateProcessingRequest) (*empty.Empty, error)
	InitiateProcessingLRO(context.Context, *InitiateProcessingRequest) (*longrunning.Operation, error)
	// Given a document (.doc, .docx, .txt, .ppt, ect.) convert it to pdf
	DocToPdf(context.Context, *DocToPdfRequest) (*DocToPdfResponse, error)
	DocToPdfLRO(context.Context, *DocToPdfRequest) (*longrunning.Operation, error)
	// Parses an email *.eml file stored as a generic file. Stores all
	// attachments as new generic files and returns the email headers, body,
	// and list of attachments.
	ParseEmail(context.Context, *ParseEmailRequest) (*ParseEmailResponse, error)
	ParseEmailLRO(context.Context, *ParseEmailRequest) (*longrunning.Operation, error)
	// Given an email *.eml file stored as a generic file, this renders the
	// email body as a pdf and stores the pdf as a new generic file.
	RenderEmailBody(context.Context, *RenderEmailBodyRequest) (*RenderEmailBodyResponse, error)
	RenderEmailBodyLRO(context.Context, *RenderEmailBodyRequest) (*longrunning.Operation, error)
	// Given a pdf file stored as a generic file, this renders the individual
	// pages of the pdf as png files and stores them as new generic files. It
	// will render them at 300 DPI.
	RenderPdf(context.Context, *RenderPdfRequest) (*RenderPdfResponse, error)
	RenderPdfLRO(context.Context, *RenderPdfRequest) (*longrunning.Operation, error)
	// Given a tiff file stored as a generic file, this splits the pages into
	// individual png files and stores them as new generic files.
	SplitTiff(context.Context, *SplitTiffRequest) (*SplitTiffResponse, error)
	SplitTiffLRO(context.Context, *SplitTiffRequest) (*longrunning.Operation, error)
	// Returns a list of available processed results (i.e., the final outputs
	// of the client/application-specific operations triggered by InitiateProcessing()
	ListResults(context.Context, *ListResultsRequest) (*ListResultsResponse, error)
	ListResultsLRO(context.Context, *ListResultsRequest) (*longrunning.Operation, error)
	// Fetch any available result.
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	GetResultLRO(context.Context, *GetResultRequest) (*longrunning.Operation, error)
	// Delete any available result.
	DeleteResult(context.Context, *DeleteResultRequest) (*empty.Empty, error)
	DeleteResultLRO(context.Context, *DeleteResultRequest) (*longrunning.Operation, error)
}

// UnimplementedFileProcessingServer can be embedded to have forward compatible implementations.
type UnimplementedFileProcessingServer struct {
}

func (*UnimplementedFileProcessingServer) UploadGenericFile(ctx context.Context, req *UploadGenericFileRequest) (*UploadGenericFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadGenericFile not implemented")
}
func (*UnimplementedFileProcessingServer) UploadGenericFileLRO(ctx context.Context, req *UploadGenericFileRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadGenericFileLRO not implemented")
}
func (*UnimplementedFileProcessingServer) GetGenericFile(ctx context.Context, req *GetGenericFileRequest) (*GetGenericFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenericFile not implemented")
}
func (*UnimplementedFileProcessingServer) GetGenericFileLRO(ctx context.Context, req *GetGenericFileRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenericFileLRO not implemented")
}
func (*UnimplementedFileProcessingServer) CreateFileset(ctx context.Context, req *CreateFilesetRequest) (*CreateFilesetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileset not implemented")
}
func (*UnimplementedFileProcessingServer) CreateFilesetLRO(ctx context.Context, req *CreateFilesetRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFilesetLRO not implemented")
}
func (*UnimplementedFileProcessingServer) InitiateProcessing(ctx context.Context, req *InitiateProcessingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateProcessing not implemented")
}
func (*UnimplementedFileProcessingServer) InitiateProcessingLRO(ctx context.Context, req *InitiateProcessingRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateProcessingLRO not implemented")
}
func (*UnimplementedFileProcessingServer) DocToPdf(ctx context.Context, req *DocToPdfRequest) (*DocToPdfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocToPdf not implemented")
}
func (*UnimplementedFileProcessingServer) DocToPdfLRO(ctx context.Context, req *DocToPdfRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocToPdfLRO not implemented")
}
func (*UnimplementedFileProcessingServer) ParseEmail(ctx context.Context, req *ParseEmailRequest) (*ParseEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseEmail not implemented")
}
func (*UnimplementedFileProcessingServer) ParseEmailLRO(ctx context.Context, req *ParseEmailRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseEmailLRO not implemented")
}
func (*UnimplementedFileProcessingServer) RenderEmailBody(ctx context.Context, req *RenderEmailBodyRequest) (*RenderEmailBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderEmailBody not implemented")
}
func (*UnimplementedFileProcessingServer) RenderEmailBodyLRO(ctx context.Context, req *RenderEmailBodyRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderEmailBodyLRO not implemented")
}
func (*UnimplementedFileProcessingServer) RenderPdf(ctx context.Context, req *RenderPdfRequest) (*RenderPdfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderPdf not implemented")
}
func (*UnimplementedFileProcessingServer) RenderPdfLRO(ctx context.Context, req *RenderPdfRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderPdfLRO not implemented")
}
func (*UnimplementedFileProcessingServer) SplitTiff(ctx context.Context, req *SplitTiffRequest) (*SplitTiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitTiff not implemented")
}
func (*UnimplementedFileProcessingServer) SplitTiffLRO(ctx context.Context, req *SplitTiffRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitTiffLRO not implemented")
}
func (*UnimplementedFileProcessingServer) ListResults(ctx context.Context, req *ListResultsRequest) (*ListResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResults not implemented")
}
func (*UnimplementedFileProcessingServer) ListResultsLRO(ctx context.Context, req *ListResultsRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResultsLRO not implemented")
}
func (*UnimplementedFileProcessingServer) GetResult(ctx context.Context, req *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}
func (*UnimplementedFileProcessingServer) GetResultLRO(ctx context.Context, req *GetResultRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResultLRO not implemented")
}
func (*UnimplementedFileProcessingServer) DeleteResult(ctx context.Context, req *DeleteResultRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResult not implemented")
}
func (*UnimplementedFileProcessingServer) DeleteResultLRO(ctx context.Context, req *DeleteResultRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResultLRO not implemented")
}

func RegisterFileProcessingServer(s *grpc.Server, srv FileProcessingServer) {
	s.RegisterService(&_FileProcessing_serviceDesc, srv)
}

func _FileProcessing_UploadGenericFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadGenericFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).UploadGenericFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/UploadGenericFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).UploadGenericFile(ctx, req.(*UploadGenericFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_UploadGenericFileLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadGenericFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).UploadGenericFileLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/UploadGenericFileLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).UploadGenericFileLRO(ctx, req.(*UploadGenericFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_GetGenericFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenericFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).GetGenericFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/GetGenericFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).GetGenericFile(ctx, req.(*GetGenericFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_GetGenericFileLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenericFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).GetGenericFileLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/GetGenericFileLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).GetGenericFileLRO(ctx, req.(*GetGenericFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_CreateFileset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).CreateFileset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/CreateFileset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).CreateFileset(ctx, req.(*CreateFilesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_CreateFilesetLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).CreateFilesetLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/CreateFilesetLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).CreateFilesetLRO(ctx, req.(*CreateFilesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_InitiateProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).InitiateProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/InitiateProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).InitiateProcessing(ctx, req.(*InitiateProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_InitiateProcessingLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).InitiateProcessingLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/InitiateProcessingLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).InitiateProcessingLRO(ctx, req.(*InitiateProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_DocToPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocToPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).DocToPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/DocToPdf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).DocToPdf(ctx, req.(*DocToPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_DocToPdfLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocToPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).DocToPdfLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/DocToPdfLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).DocToPdfLRO(ctx, req.(*DocToPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_ParseEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).ParseEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/ParseEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).ParseEmail(ctx, req.(*ParseEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_ParseEmailLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).ParseEmailLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/ParseEmailLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).ParseEmailLRO(ctx, req.(*ParseEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_RenderEmailBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderEmailBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).RenderEmailBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/RenderEmailBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).RenderEmailBody(ctx, req.(*RenderEmailBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_RenderEmailBodyLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderEmailBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).RenderEmailBodyLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/RenderEmailBodyLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).RenderEmailBodyLRO(ctx, req.(*RenderEmailBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_RenderPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).RenderPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/RenderPdf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).RenderPdf(ctx, req.(*RenderPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_RenderPdfLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).RenderPdfLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/RenderPdfLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).RenderPdfLRO(ctx, req.(*RenderPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_SplitTiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitTiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).SplitTiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/SplitTiff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).SplitTiff(ctx, req.(*SplitTiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_SplitTiffLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitTiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).SplitTiffLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/SplitTiffLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).SplitTiffLRO(ctx, req.(*SplitTiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_ListResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).ListResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/ListResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).ListResults(ctx, req.(*ListResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_ListResultsLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).ListResultsLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/ListResultsLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).ListResultsLRO(ctx, req.(*ListResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/GetResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_GetResultLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).GetResultLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/GetResultLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).GetResultLRO(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_DeleteResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).DeleteResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/DeleteResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).DeleteResult(ctx, req.(*DeleteResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessing_DeleteResultLRO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).DeleteResultLRO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsys.api.file.FileProcessing/DeleteResultLRO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).DeleteResultLRO(ctx, req.(*DeleteResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileProcessing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nsys.api.file.FileProcessing",
	HandlerType: (*FileProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadGenericFile",
			Handler:    _FileProcessing_UploadGenericFile_Handler,
		},
		{
			MethodName: "UploadGenericFileLRO",
			Handler:    _FileProcessing_UploadGenericFileLRO_Handler,
		},
		{
			MethodName: "GetGenericFile",
			Handler:    _FileProcessing_GetGenericFile_Handler,
		},
		{
			MethodName: "GetGenericFileLRO",
			Handler:    _FileProcessing_GetGenericFileLRO_Handler,
		},
		{
			MethodName: "CreateFileset",
			Handler:    _FileProcessing_CreateFileset_Handler,
		},
		{
			MethodName: "CreateFilesetLRO",
			Handler:    _FileProcessing_CreateFilesetLRO_Handler,
		},
		{
			MethodName: "InitiateProcessing",
			Handler:    _FileProcessing_InitiateProcessing_Handler,
		},
		{
			MethodName: "InitiateProcessingLRO",
			Handler:    _FileProcessing_InitiateProcessingLRO_Handler,
		},
		{
			MethodName: "DocToPdf",
			Handler:    _FileProcessing_DocToPdf_Handler,
		},
		{
			MethodName: "DocToPdfLRO",
			Handler:    _FileProcessing_DocToPdfLRO_Handler,
		},
		{
			MethodName: "ParseEmail",
			Handler:    _FileProcessing_ParseEmail_Handler,
		},
		{
			MethodName: "ParseEmailLRO",
			Handler:    _FileProcessing_ParseEmailLRO_Handler,
		},
		{
			MethodName: "RenderEmailBody",
			Handler:    _FileProcessing_RenderEmailBody_Handler,
		},
		{
			MethodName: "RenderEmailBodyLRO",
			Handler:    _FileProcessing_RenderEmailBodyLRO_Handler,
		},
		{
			MethodName: "RenderPdf",
			Handler:    _FileProcessing_RenderPdf_Handler,
		},
		{
			MethodName: "RenderPdfLRO",
			Handler:    _FileProcessing_RenderPdfLRO_Handler,
		},
		{
			MethodName: "SplitTiff",
			Handler:    _FileProcessing_SplitTiff_Handler,
		},
		{
			MethodName: "SplitTiffLRO",
			Handler:    _FileProcessing_SplitTiffLRO_Handler,
		},
		{
			MethodName: "ListResults",
			Handler:    _FileProcessing_ListResults_Handler,
		},
		{
			MethodName: "ListResultsLRO",
			Handler:    _FileProcessing_ListResultsLRO_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _FileProcessing_GetResult_Handler,
		},
		{
			MethodName: "GetResultLRO",
			Handler:    _FileProcessing_GetResultLRO_Handler,
		},
		{
			MethodName: "DeleteResult",
			Handler:    _FileProcessing_DeleteResult_Handler,
		},
		{
			MethodName: "DeleteResultLRO",
			Handler:    _FileProcessing_DeleteResultLRO_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file.proto",
}
