// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file_ntypes.proto

package ntypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawFile struct {
	// The actual file data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The 512/256 SHA sum for the data bytes.
	Sha512_256           []byte   `protobuf:"bytes,2,opt,name=sha512_256,json=sha512256,proto3" json:"sha512_256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawFile) Reset()         { *m = RawFile{} }
func (m *RawFile) String() string { return proto.CompactTextString(m) }
func (*RawFile) ProtoMessage()    {}
func (*RawFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5778cc384c232191, []int{0}
}

func (m *RawFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawFile.Unmarshal(m, b)
}
func (m *RawFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawFile.Marshal(b, m, deterministic)
}
func (m *RawFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawFile.Merge(m, src)
}
func (m *RawFile) XXX_Size() int {
	return xxx_messageInfo_RawFile.Size(m)
}
func (m *RawFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RawFile.DiscardUnknown(m)
}

var xxx_messageInfo_RawFile proto.InternalMessageInfo

func (m *RawFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RawFile) GetSha512_256() []byte {
	if m != nil {
		return m.Sha512_256
	}
	return nil
}

type GenericFile struct {
	// For client or documented application use.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// For client or documented application use.
	Metadata *any.Any `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The basename of the file on the originating system, i.e., no
	// directory path, no slashes -- the rightmost part of the name.
	OriginBasename string `protobuf:"bytes,3,opt,name=origin_basename,json=originBasename,proto3" json:"origin_basename,omitempty"`
	// Length of the file in bytes.
	// Max length is always less than a gigabyte.
	Length uint32 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	// The actual file data and its checksum.
	RawFile              *RawFile `protobuf:"bytes,5,opt,name=raw_file,json=rawFile,proto3" json:"raw_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericFile) Reset()         { *m = GenericFile{} }
func (m *GenericFile) String() string { return proto.CompactTextString(m) }
func (*GenericFile) ProtoMessage()    {}
func (*GenericFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5778cc384c232191, []int{1}
}

func (m *GenericFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericFile.Unmarshal(m, b)
}
func (m *GenericFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericFile.Marshal(b, m, deterministic)
}
func (m *GenericFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericFile.Merge(m, src)
}
func (m *GenericFile) XXX_Size() int {
	return xxx_messageInfo_GenericFile.Size(m)
}
func (m *GenericFile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericFile.DiscardUnknown(m)
}

var xxx_messageInfo_GenericFile proto.InternalMessageInfo

func (m *GenericFile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GenericFile) GetMetadata() *any.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GenericFile) GetOriginBasename() string {
	if m != nil {
		return m.OriginBasename
	}
	return ""
}

func (m *GenericFile) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *GenericFile) GetRawFile() *RawFile {
	if m != nil {
		return m.RawFile
	}
	return nil
}

type ParsedEmail struct {
	// The email headers
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The email body (html/text)
	EmailBody string `protobuf:"bytes,2,opt,name=email_body,json=emailBody,proto3" json:"email_body,omitempty"`
	// The saved attachment generic file IDs
	Attachments []*EmailAttachment `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// The attachments that were rejected due to their file extensions not
	// being in the given whitelist.
	RejectedAttachments []*EmailAttachment `protobuf:"bytes,4,rep,name=rejected_attachments,json=rejectedAttachments,proto3" json:"rejected_attachments,omitempty"`
	// The saved inline attachments
	InlineAttachments []*EmailAttachment `protobuf:"bytes,5,rep,name=inline_attachments,json=inlineAttachments,proto3" json:"inline_attachments,omitempty"`
	// The inline attachments that were rejected due to their file extensions
	// not being in the given whitelist.
	RejectedInlineAttachments []*EmailAttachment `protobuf:"bytes,6,rep,name=rejected_inline_attachments,json=rejectedInlineAttachments,proto3" json:"rejected_inline_attachments,omitempty"`
	// A specialized hash calculated from the email body and attachments (but
	// not the headers). It can be used to check for duplicated emails.
	EmailHash            string   `protobuf:"bytes,7,opt,name=email_hash,json=emailHash,proto3" json:"email_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParsedEmail) Reset()         { *m = ParsedEmail{} }
func (m *ParsedEmail) String() string { return proto.CompactTextString(m) }
func (*ParsedEmail) ProtoMessage()    {}
func (*ParsedEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5778cc384c232191, []int{2}
}

func (m *ParsedEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParsedEmail.Unmarshal(m, b)
}
func (m *ParsedEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParsedEmail.Marshal(b, m, deterministic)
}
func (m *ParsedEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParsedEmail.Merge(m, src)
}
func (m *ParsedEmail) XXX_Size() int {
	return xxx_messageInfo_ParsedEmail.Size(m)
}
func (m *ParsedEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_ParsedEmail.DiscardUnknown(m)
}

var xxx_messageInfo_ParsedEmail proto.InternalMessageInfo

func (m *ParsedEmail) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ParsedEmail) GetEmailBody() string {
	if m != nil {
		return m.EmailBody
	}
	return ""
}

func (m *ParsedEmail) GetAttachments() []*EmailAttachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *ParsedEmail) GetRejectedAttachments() []*EmailAttachment {
	if m != nil {
		return m.RejectedAttachments
	}
	return nil
}

func (m *ParsedEmail) GetInlineAttachments() []*EmailAttachment {
	if m != nil {
		return m.InlineAttachments
	}
	return nil
}

func (m *ParsedEmail) GetRejectedInlineAttachments() []*EmailAttachment {
	if m != nil {
		return m.RejectedInlineAttachments
	}
	return nil
}

func (m *ParsedEmail) GetEmailHash() string {
	if m != nil {
		return m.EmailHash
	}
	return ""
}

type EmailAttachment struct {
	// The generic file id of the saved attachment.  If empty, then the file
	// was not saved.
	GenericFileName string `protobuf:"bytes,1,opt,name=generic_file_name,json=genericFileName,proto3" json:"generic_file_name,omitempty"`
	// The supplied file name for the attachment, as found in the email.
	SuppliedName string `protobuf:"bytes,2,opt,name=supplied_name,json=suppliedName,proto3" json:"supplied_name,omitempty"`
	// The attachment size in bytes, if rejected it will be zero.
	Size                 uint32   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAttachment) Reset()         { *m = EmailAttachment{} }
func (m *EmailAttachment) String() string { return proto.CompactTextString(m) }
func (*EmailAttachment) ProtoMessage()    {}
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5778cc384c232191, []int{3}
}

func (m *EmailAttachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAttachment.Unmarshal(m, b)
}
func (m *EmailAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAttachment.Marshal(b, m, deterministic)
}
func (m *EmailAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAttachment.Merge(m, src)
}
func (m *EmailAttachment) XXX_Size() int {
	return xxx_messageInfo_EmailAttachment.Size(m)
}
func (m *EmailAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAttachment proto.InternalMessageInfo

func (m *EmailAttachment) GetGenericFileName() string {
	if m != nil {
		return m.GenericFileName
	}
	return ""
}

func (m *EmailAttachment) GetSuppliedName() string {
	if m != nil {
		return m.SuppliedName
	}
	return ""
}

func (m *EmailAttachment) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*RawFile)(nil), "nsys.api.ntypes.RawFile")
	proto.RegisterType((*GenericFile)(nil), "nsys.api.ntypes.GenericFile")
	proto.RegisterType((*ParsedEmail)(nil), "nsys.api.ntypes.ParsedEmail")
	proto.RegisterMapType((map[string]string)(nil), "nsys.api.ntypes.ParsedEmail.HeadersEntry")
	proto.RegisterType((*EmailAttachment)(nil), "nsys.api.ntypes.EmailAttachment")
}

func init() { proto.RegisterFile("file_ntypes.proto", fileDescriptor_5778cc384c232191) }

var fileDescriptor_5778cc384c232191 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xe6, 0x5f, 0x33, 0x4e, 0x08, 0x59, 0x22, 0xe4, 0x16, 0x21, 0x45, 0xe1, 0x40,
	0xe0, 0xe0, 0x40, 0xaa, 0x54, 0xa8, 0xe2, 0x92, 0xa0, 0x42, 0xb9, 0x00, 0x5a, 0x6e, 0x5c, 0xcc,
	0x26, 0x9e, 0xda, 0x0b, 0xce, 0xda, 0xda, 0xdd, 0xb4, 0x32, 0x4f, 0xc2, 0x9b, 0xf1, 0x3a, 0xc8,
	0xbb, 0x71, 0x30, 0x4d, 0x0f, 0xb9, 0xad, 0x67, 0x67, 0x7e, 0xdf, 0xf8, 0xdb, 0x19, 0xe8, 0x5f,
	0xf3, 0x04, 0x03, 0xa1, 0xf3, 0x0c, 0x95, 0x9f, 0xc9, 0x54, 0xa7, 0xa4, 0x27, 0x54, 0xae, 0x7c,
	0x96, 0x71, 0xdf, 0x86, 0x4f, 0x4f, 0xa2, 0x34, 0x8d, 0x12, 0x9c, 0x98, 0xeb, 0xe5, 0xe6, 0x7a,
	0xc2, 0x44, 0x6e, 0x73, 0x47, 0x6f, 0xa1, 0x45, 0xd9, 0xed, 0x7b, 0x9e, 0x20, 0x21, 0x50, 0x0f,
	0x99, 0x66, 0x9e, 0x33, 0x74, 0xc6, 0x1d, 0x6a, 0xce, 0xe4, 0x29, 0x80, 0x8a, 0xd9, 0xec, 0xf5,
	0x34, 0x98, 0xce, 0xce, 0xbd, 0x23, 0x73, 0xd3, 0xb6, 0x91, 0xe9, 0xec, 0x7c, 0xf4, 0xc7, 0x01,
	0xf7, 0x03, 0x0a, 0x94, 0x7c, 0x65, 0x10, 0x43, 0x70, 0x43, 0x54, 0x2b, 0xc9, 0x33, 0xcd, 0x53,
	0x61, 0x48, 0x6d, 0x5a, 0x0d, 0x91, 0x57, 0x70, 0xbc, 0x46, 0xcd, 0x8c, 0x50, 0x81, 0x73, 0xa7,
	0x03, 0xdf, 0x76, 0xe7, 0x97, 0xdd, 0xf9, 0x73, 0x91, 0xd3, 0x5d, 0x16, 0x79, 0x0e, 0xbd, 0x54,
	0xf2, 0x88, 0x8b, 0x60, 0xc9, 0x14, 0x0a, 0xb6, 0x46, 0xaf, 0x66, 0xb8, 0x0f, 0x6c, 0x78, 0xb1,
	0x8d, 0x92, 0xc7, 0xd0, 0x4c, 0x50, 0x44, 0x3a, 0xf6, 0xea, 0x43, 0x67, 0xdc, 0xa5, 0xdb, 0x2f,
	0x72, 0x06, 0xc7, 0x92, 0xdd, 0x06, 0x85, 0x4f, 0x5e, 0xc3, 0x48, 0x7a, 0xfe, 0x1d, 0x87, 0xfc,
	0xad, 0x07, 0xb4, 0x25, 0xed, 0x61, 0xf4, 0xbb, 0x0e, 0xee, 0x17, 0x26, 0x15, 0x86, 0x97, 0x6b,
	0xc6, 0x13, 0xf2, 0x0e, 0x5a, 0x31, 0xb2, 0x10, 0xa5, 0xf2, 0x9c, 0x61, 0x6d, 0xec, 0x4e, 0x5f,
	0xec, 0x31, 0x2a, 0xe9, 0xfe, 0x95, 0xcd, 0xbd, 0x14, 0x5a, 0xe6, 0xb4, 0xac, 0x2c, 0xdc, 0xc4,
	0xe2, 0x3a, 0x58, 0xa6, 0x61, 0x6e, 0x7e, 0xbf, 0x4d, 0xdb, 0x26, 0xb2, 0x48, 0xc3, 0x9c, 0x2c,
	0xc0, 0x65, 0x5a, 0xb3, 0x55, 0xbc, 0x46, 0xa1, 0x95, 0x57, 0x33, 0x3a, 0xc3, 0x3d, 0x1d, 0xa3,
	0x30, 0xdf, 0x25, 0xd2, 0x6a, 0x11, 0xf9, 0x0a, 0x03, 0x89, 0x3f, 0x70, 0xa5, 0x31, 0x0c, 0xaa,
	0xb0, 0xfa, 0x81, 0xb0, 0x47, 0x65, 0xf5, 0xbc, 0x02, 0xfd, 0x0c, 0x84, 0x8b, 0x84, 0x0b, 0xfc,
	0x0f, 0xd9, 0x38, 0x10, 0xd9, 0xb7, 0xb5, 0x55, 0xe0, 0x77, 0x78, 0xb2, 0xeb, 0xf2, 0x1e, 0x72,
	0xf3, 0x40, 0xf2, 0x49, 0x09, 0xf9, 0xb8, 0xa7, 0xb0, 0xb3, 0x3a, 0x66, 0x2a, 0xf6, 0x5a, 0x15,
	0xab, 0xaf, 0x98, 0x8a, 0x4f, 0x2f, 0xa0, 0x53, 0x7d, 0x22, 0xf2, 0x10, 0x6a, 0x3f, 0x31, 0xdf,
	0x0e, 0x6c, 0x71, 0x24, 0x03, 0x68, 0xdc, 0xb0, 0x64, 0x83, 0xdb, 0x67, 0xb2, 0x1f, 0x17, 0x47,
	0x6f, 0x9c, 0xd1, 0x0d, 0xf4, 0xee, 0x34, 0x42, 0x5e, 0x42, 0x3f, 0xb2, 0x6b, 0x10, 0xd8, 0x75,
	0x2c, 0xa6, 0xd4, 0xc2, 0x7a, 0xd1, 0xbf, 0xfd, 0xf8, 0x54, 0x8c, 0xe9, 0x33, 0xe8, 0xaa, 0x4d,
	0x96, 0x25, 0x1c, 0x43, 0x9b, 0x67, 0x05, 0x3a, 0x65, 0xd0, 0x24, 0x11, 0xa8, 0x2b, 0xfe, 0xcb,
	0x4e, 0x7a, 0x97, 0x9a, 0xf3, 0x62, 0xf0, 0x8d, 0x18, 0x43, 0x78, 0x3a, 0x61, 0x19, 0x9f, 0x58,
	0x4f, 0x96, 0x4d, 0xb3, 0x36, 0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xba, 0x6a, 0xcb, 0xc4,
	0x08, 0x04, 0x00, 0x00,
}
