// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sig_present.proto

package ntypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignaturePresentPuzzle struct {
	// This should be a tightly cut area defining where the bulk of any
	// signature should be found. The bottom of the rectangle is the
	// expected baseline of the signature (whether or not there is an
	// actual line appearing on the paper). The top of the rectangle
	// should be the *typical* upper bound.
	// The system automatically expands its search area beyond these
	// bounds to capture ascenders and descenders.
	//
	// Types that are valid to be assigned to SignatureArea:
	//	*SignaturePresentPuzzle_RotatedRect
	//	*SignaturePresentPuzzle_Rect
	SignatureArea        isSignaturePresentPuzzle_SignatureArea `protobuf_oneof:"signature_area"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *SignaturePresentPuzzle) Reset()         { *m = SignaturePresentPuzzle{} }
func (m *SignaturePresentPuzzle) String() string { return proto.CompactTextString(m) }
func (*SignaturePresentPuzzle) ProtoMessage()    {}
func (*SignaturePresentPuzzle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ef63e3f8d08292, []int{0}
}

func (m *SignaturePresentPuzzle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignaturePresentPuzzle.Unmarshal(m, b)
}
func (m *SignaturePresentPuzzle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignaturePresentPuzzle.Marshal(b, m, deterministic)
}
func (m *SignaturePresentPuzzle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignaturePresentPuzzle.Merge(m, src)
}
func (m *SignaturePresentPuzzle) XXX_Size() int {
	return xxx_messageInfo_SignaturePresentPuzzle.Size(m)
}
func (m *SignaturePresentPuzzle) XXX_DiscardUnknown() {
	xxx_messageInfo_SignaturePresentPuzzle.DiscardUnknown(m)
}

var xxx_messageInfo_SignaturePresentPuzzle proto.InternalMessageInfo

type isSignaturePresentPuzzle_SignatureArea interface {
	isSignaturePresentPuzzle_SignatureArea()
}

type SignaturePresentPuzzle_RotatedRect struct {
	RotatedRect *RotatedRectangle `protobuf:"bytes,1,opt,name=rotated_rect,json=rotatedRect,proto3,oneof"`
}

type SignaturePresentPuzzle_Rect struct {
	Rect *Rectangle `protobuf:"bytes,2,opt,name=rect,proto3,oneof"`
}

func (*SignaturePresentPuzzle_RotatedRect) isSignaturePresentPuzzle_SignatureArea() {}

func (*SignaturePresentPuzzle_Rect) isSignaturePresentPuzzle_SignatureArea() {}

func (m *SignaturePresentPuzzle) GetSignatureArea() isSignaturePresentPuzzle_SignatureArea {
	if m != nil {
		return m.SignatureArea
	}
	return nil
}

func (m *SignaturePresentPuzzle) GetRotatedRect() *RotatedRectangle {
	if x, ok := m.GetSignatureArea().(*SignaturePresentPuzzle_RotatedRect); ok {
		return x.RotatedRect
	}
	return nil
}

func (m *SignaturePresentPuzzle) GetRect() *Rectangle {
	if x, ok := m.GetSignatureArea().(*SignaturePresentPuzzle_Rect); ok {
		return x.Rect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignaturePresentPuzzle) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignaturePresentPuzzle_RotatedRect)(nil),
		(*SignaturePresentPuzzle_Rect)(nil),
	}
}

type SignaturePresentCut struct {
	// The raw cut image defined by the signature area in SignaturePresentPuzzle.
	RawCut *DimensionedImage `protobuf:"bytes,1,opt,name=raw_cut,json=rawCut,proto3" json:"raw_cut,omitempty"`
	// The context cut image (potentially larger than defined cut on exemplar).
	ContextCut *DimensionedImage `protobuf:"bytes,2,opt,name=context_cut,json=contextCut,proto3" json:"context_cut,omitempty"`
	// The rectangle inside the context image where the raw cut is located.
	ContextRect          *Rectangle `protobuf:"bytes,3,opt,name=context_rect,json=contextRect,proto3" json:"context_rect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignaturePresentCut) Reset()         { *m = SignaturePresentCut{} }
func (m *SignaturePresentCut) String() string { return proto.CompactTextString(m) }
func (*SignaturePresentCut) ProtoMessage()    {}
func (*SignaturePresentCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ef63e3f8d08292, []int{1}
}

func (m *SignaturePresentCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignaturePresentCut.Unmarshal(m, b)
}
func (m *SignaturePresentCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignaturePresentCut.Marshal(b, m, deterministic)
}
func (m *SignaturePresentCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignaturePresentCut.Merge(m, src)
}
func (m *SignaturePresentCut) XXX_Size() int {
	return xxx_messageInfo_SignaturePresentCut.Size(m)
}
func (m *SignaturePresentCut) XXX_DiscardUnknown() {
	xxx_messageInfo_SignaturePresentCut.DiscardUnknown(m)
}

var xxx_messageInfo_SignaturePresentCut proto.InternalMessageInfo

func (m *SignaturePresentCut) GetRawCut() *DimensionedImage {
	if m != nil {
		return m.RawCut
	}
	return nil
}

func (m *SignaturePresentCut) GetContextCut() *DimensionedImage {
	if m != nil {
		return m.ContextCut
	}
	return nil
}

func (m *SignaturePresentCut) GetContextRect() *Rectangle {
	if m != nil {
		return m.ContextRect
	}
	return nil
}

type SignaturePresentHint struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignaturePresentHint) Reset()         { *m = SignaturePresentHint{} }
func (m *SignaturePresentHint) String() string { return proto.CompactTextString(m) }
func (*SignaturePresentHint) ProtoMessage()    {}
func (*SignaturePresentHint) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ef63e3f8d08292, []int{2}
}

func (m *SignaturePresentHint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignaturePresentHint.Unmarshal(m, b)
}
func (m *SignaturePresentHint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignaturePresentHint.Marshal(b, m, deterministic)
}
func (m *SignaturePresentHint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignaturePresentHint.Merge(m, src)
}
func (m *SignaturePresentHint) XXX_Size() int {
	return xxx_messageInfo_SignaturePresentHint.Size(m)
}
func (m *SignaturePresentHint) XXX_DiscardUnknown() {
	xxx_messageInfo_SignaturePresentHint.DiscardUnknown(m)
}

var xxx_messageInfo_SignaturePresentHint proto.InternalMessageInfo

type SignaturePresentSolution struct {
	Present              bool     `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignaturePresentSolution) Reset()         { *m = SignaturePresentSolution{} }
func (m *SignaturePresentSolution) String() string { return proto.CompactTextString(m) }
func (*SignaturePresentSolution) ProtoMessage()    {}
func (*SignaturePresentSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ef63e3f8d08292, []int{3}
}

func (m *SignaturePresentSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignaturePresentSolution.Unmarshal(m, b)
}
func (m *SignaturePresentSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignaturePresentSolution.Marshal(b, m, deterministic)
}
func (m *SignaturePresentSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignaturePresentSolution.Merge(m, src)
}
func (m *SignaturePresentSolution) XXX_Size() int {
	return xxx_messageInfo_SignaturePresentSolution.Size(m)
}
func (m *SignaturePresentSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_SignaturePresentSolution.DiscardUnknown(m)
}

var xxx_messageInfo_SignaturePresentSolution proto.InternalMessageInfo

func (m *SignaturePresentSolution) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

func init() {
	proto.RegisterType((*SignaturePresentPuzzle)(nil), "nsys.api.ntypes.SignaturePresentPuzzle")
	proto.RegisterType((*SignaturePresentCut)(nil), "nsys.api.ntypes.SignaturePresentCut")
	proto.RegisterType((*SignaturePresentHint)(nil), "nsys.api.ntypes.SignaturePresentHint")
	proto.RegisterType((*SignaturePresentSolution)(nil), "nsys.api.ntypes.SignaturePresentSolution")
}

func init() { proto.RegisterFile("sig_present.proto", fileDescriptor_b4ef63e3f8d08292) }

var fileDescriptor_b4ef63e3f8d08292 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0x95, 0x56, 0xa6, 0xc5, 0x3f, 0x6b, 0x29, 0xa5, 0x27, 0x1b, 0x10, 0x3c, 0xa5,
	0xa2, 0x9e, 0x04, 0x2f, 0x55, 0xa4, 0xde, 0xca, 0xf6, 0xe6, 0x25, 0xac, 0xe9, 0x10, 0x16, 0x9a,
	0xdd, 0xb0, 0x3b, 0xa1, 0xa6, 0x9f, 0xc7, 0x8f, 0xe4, 0x07, 0x92, 0xec, 0x36, 0x28, 0xa9, 0xa2,
	0xc7, 0x7d, 0xbc, 0xdf, 0xcc, 0x7b, 0xcc, 0xc2, 0xa9, 0x95, 0x69, 0x9c, 0x1b, 0xb4, 0xa8, 0x28,
	0xca, 0x8d, 0x26, 0xcd, 0x8e, 0x95, 0x2d, 0x6d, 0x24, 0x72, 0x19, 0x29, 0x2a, 0x73, 0xb4, 0xa3,
	0xb1, 0x13, 0xa4, 0x9e, 0x88, 0x5c, 0x4e, 0xbc, 0x36, 0x49, 0x51, 0x67, 0x48, 0xa6, 0xf4, 0xcc,
	0xe8, 0xe2, 0x07, 0x8b, 0xcc, 0x44, 0x8a, 0xb1, 0x7f, 0x78, 0x5b, 0xf8, 0x1e, 0xc0, 0x60, 0x21,
	0x53, 0x25, 0xa8, 0x30, 0x38, 0xf7, 0x5b, 0xe7, 0xc5, 0x66, 0xb3, 0x42, 0xf6, 0x04, 0x3d, 0xa3,
	0x49, 0x10, 0x2e, 0x63, 0x83, 0x09, 0x0d, 0x83, 0xf3, 0xe0, 0xb2, 0x7b, 0x3d, 0x8e, 0x1a, 0x61,
	0x22, 0xee, 0x4d, 0x1c, 0x13, 0x12, 0x2a, 0x5d, 0xe1, 0x6c, 0x8f, 0x77, 0xcd, 0x97, 0xc6, 0xae,
	0xe0, 0xc0, 0xf1, 0x2d, 0xc7, 0x8f, 0x76, 0xf9, 0x6f, 0xa0, 0x73, 0x4e, 0x4f, 0xe0, 0xc8, 0xd6,
	0x99, 0x62, 0x61, 0x50, 0x84, 0x1f, 0x01, 0x9c, 0x35, 0x63, 0x3e, 0x14, 0xc4, 0xee, 0xa0, 0x63,
	0xc4, 0x3a, 0x4e, 0x8a, 0xdf, 0xe3, 0x3d, 0xca, 0x0c, 0x95, 0x95, 0x5a, 0xe1, 0xf2, 0xb9, 0xea,
	0xcf, 0xdb, 0x46, 0xac, 0x2b, 0x76, 0x0a, 0xdd, 0x44, 0x2b, 0xc2, 0x37, 0x72, 0x7c, 0xeb, 0xbf,
	0x3c, 0x6c, 0xa9, 0x6a, 0xc6, 0x3d, 0xf4, 0xea, 0x19, 0xae, 0xe3, 0xfe, 0x5f, 0x1d, 0x79, 0xbd,
	0xb3, 0x52, 0xc2, 0x01, 0xf4, 0x9b, 0xad, 0x66, 0x52, 0x51, 0x78, 0x0b, 0xc3, 0xa6, 0xbe, 0xd0,
	0xab, 0x82, 0xa4, 0x56, 0x6c, 0x08, 0x9d, 0xed, 0xef, 0x70, 0x95, 0x0f, 0x79, 0xfd, 0x9c, 0xf6,
	0x5f, 0xd8, 0xee, 0xd1, 0x5f, 0xdb, 0xee, 0xd0, 0x37, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45,
	0xa6, 0x23, 0x09, 0x58, 0x02, 0x00, 0x00,
}
